branch-defaults:
  master:
    environment: Classline-academy-env
environment-defaults:
  Classline-academy-env:
    branch: null
    repository: null
global:
  application_name: ClasslineAcademy
  default_ec2_keyname: classline-eb-key
  default_platform: Python 3.7 running on 64bit Amazon Linux 2
  default_region: eu-west-3
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  sc: git
  workspace_type: Application
