from .benefits import *
from .prices import *
from .languages import *
from .programs import *
from .videos import *
from .podcasts import *
from .playlists import *
from .playlists_admin import *
# from .courses import *
from .students import *
from .accounts_created import *
from .ratings import *
from .folders import *
from .files import *
from .posts import *
from .comments import *
from .instructors import *
from .allowed_programs import *
from .events import *
from .event_students import *
from .packs import *
from .packs_prices import *
from .packs_languages import *
from .videos_pack import *
from .podcasts_pack import *
from .program_topics import *
from .videos_topic import *
from .podcasts_topic import *
from .playlists_topic import *
from .courses import *