# Generated by Django 3.0.3 on 2020-08-17 17:14

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PromotionCode',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Date time on which the object was created.', verbose_name='created at')),
                ('modified', models.DateTimeField(auto_now=True, help_text='Date time on which the object was last modified.', verbose_name='modified at')),
                ('promotion_code_id', models.CharField(max_length=50)),
                ('active', models.BooleanField(default=True)),
                ('coupon_id', models.CharField(max_length=50)),
                ('code', models.CharField(max_length=50)),
                ('percent_off', models.PositiveIntegerField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created', '-modified'],
                'get_latest_by': 'created',
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='coupon',
            name='valid',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='discount',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teacher_coupons', to='users.Coupon'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='subscriptions',
            field=models.ManyToManyField(blank=True, related_name='instructor_subscriptions', to='users.Subscription'),
        ),
    ]
