# Generated by Django 3.0.3 on 2020-08-28 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200828_1554'),
    ]

    operations = [
        migrations.AddField(
            model_name='commercial',
            name='can_create_commercials',
            field=models.BooleanField(default=False),
        ),
    ]
