# Generated by Django 3.0.3 on 2020-08-17 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200817_1914'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='application_fee_percent',
            field=models.PositiveIntegerField(default=25),
        ),
    ]
