# Generated by Django 3.0.3 on 2020-09-30 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200929_1735'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='admin',
        ),
    ]
