# Generated by Django 3.0.3 on 2020-09-30 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_subscription_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='accounts_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='teacher',
            name='accounts_subscription_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='currency',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
    ]
