# Generated by Django 3.0.3 on 2020-08-20 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_teacher_application_fee_percent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='subscriptions',
            field=models.ManyToManyField(blank=True, related_name='student_subscriptions', to='users.Subscription'),
        ),
    ]
