# Generated by Django 3.0.3 on 2020-09-30 21:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20200930_2356'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='accounts_subscription_id',
        ),
    ]
