# Generated by Django 3.0.3 on 2020-09-30 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_remove_teacher_accounts_subscription_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='accounts_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
    ]
