# Generated by Django 3.0.3 on 2020-10-22 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_auto_20201022_0843'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseditem',
            name='platform_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
