# Generated by Django 3.0.3 on 2020-08-28 20:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('programs', '0001_initial'),
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='rating',
            name='rated_program',
            field=models.ForeignKey(help_text='Program that receives the rating.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rated_program', to='programs.Program'),
        ),
        migrations.AddField(
            model_name='rating',
            name='rating_user',
            field=models.ForeignKey(help_text='User that emits the rating', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rating_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='rating',
            name='related_instructor',
            field=models.ForeignKey(help_text='Instructor that receives the rating.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='related_intructor', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='programprice',
            name='program',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='programs.Program'),
        ),
        migrations.AddField(
            model_name='programlanguage',
            name='program',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='programs.Program'),
        ),
        migrations.AddField(
            model_name='program',
            name='created_accounts',
            field=models.ManyToManyField(related_name='program_accounts_created', through='programs.AccountCreated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='program',
            name='students',
            field=models.ManyToManyField(through='programs.Student', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='program',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='program_teacher', to='users.Teacher'),
        ),
        migrations.AddField(
            model_name='program',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='program_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='podcast',
            name='program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='program_podcasts', to='programs.Program'),
        ),
        migrations.AddField(
            model_name='playlisttrack',
            name='playlist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='programs.Playlist'),
        ),
        migrations.AddField(
            model_name='playlisttrack',
            name='video',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='programs.Video'),
        ),
        migrations.AddField(
            model_name='playlist',
            name='program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='program_playlist', to='programs.Program'),
        ),
        migrations.AddField(
            model_name='playlist',
            name='tracks',
            field=models.ManyToManyField(through='programs.PlaylistTrack', to='programs.Video'),
        ),
        migrations.AddField(
            model_name='event',
            name='program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='programs.Program'),
        ),
        migrations.AddField(
            model_name='benefit',
            name='program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='programs.Program'),
        ),
        migrations.AddField(
            model_name='accountcreated',
            name='program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='programs.Program'),
        ),
        migrations.AddField(
            model_name='accountcreated',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
