# Generated by Django 3.0.3 on 2020-09-04 07:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('programs', '0002_auto_20200902_1019'),
    ]

    operations = [
        migrations.CreateModel(
            name='Folder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Date time on which the object was created.', verbose_name='created at')),
                ('modified', models.DateTimeField(auto_now=True, help_text='Date time on which the object was last modified.', verbose_name='modified at')),
                ('code', models.CharField(blank=True, max_length=10, null=True)),
                ('name', models.CharField(default='', max_length=100)),
                ('is_private', models.BooleanField(default=False)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='program_folders', to='programs.Program')),
                ('shared_users', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
                ('top_folder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='folders_folder', to='programs.Program')),
            ],
            options={
                'ordering': ['-created', '-modified'],
                'get_latest_by': 'created',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Date time on which the object was created.', verbose_name='created at')),
                ('modified', models.DateTimeField(auto_now=True, help_text='Date time on which the object was last modified.', verbose_name='modified at')),
                ('code', models.CharField(blank=True, max_length=10, null=True)),
                ('name', models.CharField(default='', max_length=100)),
                ('is_private', models.BooleanField(default=False)),
                ('file', models.FileField(max_length=500, upload_to='programs/documents/files/')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='program_files', to='programs.Program')),
                ('shared_users', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
                ('top_folder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files_folder', to='programs.Program')),
            ],
            options={
                'ordering': ['-created', '-modified'],
                'get_latest_by': 'created',
                'abstract': False,
            },
        ),
    ]
