# Generated by Django 3.0.3 on 2020-08-29 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0002_auto_20200828_2204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='programs/videos/pictures/', verbose_name='profile picture'),
        ),
    ]
