# Generated by Django 3.0.3 on 2020-09-04 07:45

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0003_file_folder'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Date time on which the object was created.', verbose_name='created at')),
                ('modified', models.DateTimeField(auto_now=True, help_text='Date time on which the object was last modified.', verbose_name='modified at')),
                ('subscription_id', models.CharField(blank=True, max_length=100, null=True)),
                ('to_be_cancelled', models.BooleanField()),
                ('cancelled', models.BooleanField(default=False)),
                ('payment_issue', models.BooleanField(default=False)),
                ('current_period_end', models.IntegerField(blank=True, default=0)),
                ('user', models.CharField(max_length=100)),
                ('program', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['-created', '-modified'],
                'get_latest_by': 'created',
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='file',
            name='top_folder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='files_folder', to='programs.Program'),
        ),
        migrations.AlterField(
            model_name='folder',
            name='top_folder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='folders_folder', to='programs.Program'),
        ),
    ]
