# Generated by Django 3.0.3 on 2020-08-30 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0003_auto_20200829_1138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='benefit',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='title',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='picture',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to='programs/playlists/pictures/', verbose_name='profile picture'),
        ),
        migrations.AlterField(
            model_name='podcast',
            name='audio',
            field=models.FileField(max_length=500, upload_to='programs/podcasts/videos/', verbose_name='podcast audio'),
        ),
        migrations.AlterField(
            model_name='podcast',
            name='picture',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to='programs/podcasts/pictures/', verbose_name='podcast picture'),
        ),
        migrations.AlterField(
            model_name='podcast',
            name='title',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='program',
            name='picture',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to='programs/pictures/', verbose_name='profile picture'),
        ),
        migrations.AlterField(
            model_name='program',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='program',
            name='video_presentation',
            field=models.FileField(blank=True, max_length=500, null=True, upload_to='programs/videos/', verbose_name='profile video'),
        ),
        migrations.AlterField(
            model_name='video',
            name='picture',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to='programs/videos/pictures/', verbose_name='profile picture'),
        ),
        migrations.AlterField(
            model_name='video',
            name='title',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='video',
            name='video',
            field=models.FileField(max_length=500, upload_to='programs/videos/videos/', verbose_name='profile video'),
        ),
    ]
