# Generated by Django 3.0.3 on 2020-09-02 05:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0003_auto_20200901_2147'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coursetrack',
            old_name='Course',
            new_name='course',
        ),
    ]
