# Generated by Django 3.0.3 on 2020-09-02 05:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0004_auto_20200902_0715'),
    ]

    operations = [
        migrations.RenameField(
            model_name='program',
            old_name='are_playlists',
            new_name='are_courses',
        ),
    ]
