# Generated by Django 3.0.3 on 2020-09-04 16:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0004_auto_20200904_0945'),
    ]

    operations = [
        migrations.AlterField(
            model_name='folder',
            name='top_folder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='folders_folder', to='programs.Folder'),
        ),
    ]
