# Generated by Django 3.0.3 on 2020-09-04 17:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0005_auto_20200904_1830'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='top_folder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='files_folder', to='programs.Folder'),
        ),
    ]
