# Generated by Django 3.0.3 on 2020-09-30 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0008_auto_20200930_1620'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructor',
            name='allowed_programs',
            field=models.ManyToManyField(through='programs.AllowedProgram', to='programs.Program'),
        ),
    ]
