# Generated by Django 3.0.3 on 2020-10-01 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0009_instructor_allowed_programs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coursetrack',
            name='course',
        ),
        migrations.RemoveField(
            model_name='coursetrack',
            name='video',
        ),
        migrations.DeleteModel(
            name='Course',
        ),
        migrations.DeleteModel(
            name='CourseTrack',
        ),
    ]
