# Generated by Django 3.0.3 on 2020-10-02 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0010_auto_20201001_2156'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='are_admin_playlists',
            field=models.BooleanField(default=True),
        ),
    ]
