# Generated by Django 3.0.3 on 2020-10-04 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0012_auto_20201004_1446'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='can_be_booked',
            new_name='bookable',
        ),
    ]
