# Generated by Django 3.0.3 on 2020-10-05 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0013_auto_20201004_1902'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='current_students',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
