# Generated by Django 3.0.3 on 2020-10-06 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0014_auto_20201005_1212'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_buyed',
            field=models.BooleanField(default=False),
        ),
    ]
