# Generated by Django 3.0.3 on 2020-10-06 18:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0016_auto_20201006_1549'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_buyed_parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='programs.Event'),
        ),
    ]
