# Generated by Django 3.0.3 on 2020-10-06 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0017_event_event_buyed_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='event_booking_calendar',
            field=models.BooleanField(default=False),
        ),
    ]
