# Generated by Django 3.0.3 on 2020-10-06 19:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0018_program_event_booking_calendar'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventstudent',
            name='program',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='programs.Program'),
        ),
    ]
