# Generated by Django 3.0.3 on 2020-10-17 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0019_eventstudent_program'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='is_private',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='podcast',
            name='is_private',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='video',
            name='is_private',
            field=models.BooleanField(default=False),
        ),
    ]
