# Generated by Django 3.0.3 on 2020-10-17 18:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_userloginactivity'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('programs', '0020_auto_20201017_1238'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pack',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Date time on which the object was created.', verbose_name='created at')),
                ('modified', models.DateTimeField(auto_now=True, help_text='Date time on which the object was last modified.', verbose_name='modified at')),
                ('code', models.CharField(blank=True, max_length=10, null=True)),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(blank=True, max_length=1000, null=True)),
                ('published', models.BooleanField(default=False)),
                ('are_videos', models.BooleanField(default=True)),
                ('are_playlists', models.BooleanField(default=True)),
                ('are_podcasts', models.BooleanField(default=True)),
                ('are_resources', models.BooleanField(default=True)),
                ('rating', models.FloatField(default=0)),
                ('picture', models.ImageField(blank=True, max_length=500, null=True, upload_to='packs/pictures/', verbose_name='profile picture')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='programs.Program')),
            ],
            options={
                'ordering': ['-created', '-modified'],
                'get_latest_by': 'created',
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='programprice',
            name='program',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='program_price', to='programs.Program'),
        ),
        migrations.CreateModel(
            name='VideoPack',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Date time on which the object was created.', verbose_name='created at')),
                ('modified', models.DateTimeField(auto_now=True, help_text='Date time on which the object was last modified.', verbose_name='modified at')),
                ('pack', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='programs.Pack')),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='programs.Video')),
            ],
            options={
                'ordering': ['-created', '-modified'],
                'get_latest_by': 'created',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StudentPack',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Date time on which the object was created.', verbose_name='created at')),
                ('modified', models.DateTimeField(auto_now=True, help_text='Date time on which the object was last modified.', verbose_name='modified at')),
                ('pack', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='programs.Pack')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created', '-modified'],
                'get_latest_by': 'created',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PackPrice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Date time on which the object was created.', verbose_name='created at')),
                ('modified', models.DateTimeField(auto_now=True, help_text='Date time on which the object was last modified.', verbose_name='modified at')),
                ('value', models.FloatField(blank=True, null=True)),
                ('type', models.CharField(blank=True, max_length=5, null=True)),
                ('level', models.PositiveIntegerField(blank=True, null=True)),
                ('label', models.CharField(blank=True, max_length=40, null=True)),
                ('pack', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pack_price', to='programs.Pack')),
            ],
            options={
                'ordering': ['-created', '-modified'],
                'get_latest_by': 'created',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PackLanguage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Date time on which the object was created.', verbose_name='created at')),
                ('modified', models.DateTimeField(auto_now=True, help_text='Date time on which the object was last modified.', verbose_name='modified at')),
                ('value', models.CharField(blank=True, max_length=10, null=True)),
                ('label', models.CharField(blank=True, max_length=100, null=True)),
                ('nativeName', models.CharField(blank=True, max_length=100, null=True)),
                ('pack', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='programs.Pack')),
            ],
            options={
                'ordering': ['-created', '-modified'],
                'get_latest_by': 'created',
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='pack',
            name='students',
            field=models.ManyToManyField(through='programs.StudentPack', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pack',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pack_teacher', to='users.Teacher'),
        ),
        migrations.AddField(
            model_name='pack',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pack_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pack',
            name='videos',
            field=models.ManyToManyField(through='programs.VideoPack', to='programs.Video'),
        ),
    ]
