# Generated by Django 3.0.3 on 2020-10-18 05:18

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0021_auto_20201017_2032'),
    ]

    operations = [
        migrations.CreateModel(
            name='PodcastPack',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Date time on which the object was created.', verbose_name='created at')),
                ('modified', models.DateTimeField(auto_now=True, help_text='Date time on which the object was last modified.', verbose_name='modified at')),
                ('pack', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='programs.Pack')),
                ('podcast', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='programs.Podcast')),
            ],
            options={
                'ordering': ['-created', '-modified'],
                'get_latest_by': 'created',
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='pack',
            name='podcasts',
            field=models.ManyToManyField(through='programs.PodcastPack', to='programs.Podcast'),
        ),
    ]
