# Generated by Django 3.0.3 on 2020-10-22 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0023_event_online_class'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='brand_color',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
