# Generated by Django 3.0.3 on 2020-10-26 07:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0011_purchaseditem_platform_fee'),
        ('programs', '0024_program_brand_color'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlaylistTopic',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Date time on which the object was created.', verbose_name='created at')),
                ('modified', models.DateTimeField(auto_now=True, help_text='Date time on which the object was last modified.', verbose_name='modified at')),
            ],
            options={
                'ordering': ['-created', '-modified'],
                'get_latest_by': 'created',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PodcastTopic',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Date time on which the object was created.', verbose_name='created at')),
                ('modified', models.DateTimeField(auto_now=True, help_text='Date time on which the object was last modified.', verbose_name='modified at')),
                ('podcast', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='programs.Podcast')),
            ],
            options={
                'ordering': ['-created', '-modified'],
                'get_latest_by': 'created',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProgramTopic',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Date time on which the object was created.', verbose_name='created at')),
                ('modified', models.DateTimeField(auto_now=True, help_text='Date time on which the object was last modified.', verbose_name='modified at')),
                ('code', models.CharField(blank=True, max_length=10, null=True)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('picture', models.ImageField(blank=True, max_length=500, null=True, upload_to='topics/pictures/', verbose_name='profile picture')),
                ('color', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'ordering': ['-created', '-modified'],
                'get_latest_by': 'created',
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='playlistadmin',
            name='picture',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to='programs/playlists_admin/pictures/', verbose_name='profile picture'),
        ),
        migrations.CreateModel(
            name='VideoTopic',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Date time on which the object was created.', verbose_name='created at')),
                ('modified', models.DateTimeField(auto_now=True, help_text='Date time on which the object was last modified.', verbose_name='modified at')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='programs.ProgramTopic')),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='programs.Video')),
            ],
            options={
                'ordering': ['-created', '-modified'],
                'get_latest_by': 'created',
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='programtopic',
            name='playlists',
            field=models.ManyToManyField(through='programs.PlaylistTopic', to='programs.PlaylistAdmin'),
        ),
        migrations.AddField(
            model_name='programtopic',
            name='podcasts',
            field=models.ManyToManyField(through='programs.PodcastTopic', to='programs.Podcast'),
        ),
        migrations.AddField(
            model_name='programtopic',
            name='program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='programs.Program'),
        ),
        migrations.AddField(
            model_name='programtopic',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_videos_teacher', to='users.Teacher'),
        ),
        migrations.AddField(
            model_name='programtopic',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_videos_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='programtopic',
            name='videos',
            field=models.ManyToManyField(through='programs.VideoTopic', to='programs.Video'),
        ),
        migrations.AddField(
            model_name='podcasttopic',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='programs.ProgramTopic'),
        ),
        migrations.AddField(
            model_name='playlisttopic',
            name='playlist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='programs.PlaylistAdmin'),
        ),
        migrations.AddField(
            model_name='playlisttopic',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='programs.ProgramTopic'),
        ),
    ]
