# Generated by Django 3.0.3 on 2020-10-30 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0025_auto_20201026_0834'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='bytes',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='video',
            name='mega_bytes',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='playlistadmin',
            name='picture',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to='programs/playlists_admin/pictures/', verbose_name='playlist picture'),
        ),
    ]
