# Generated by Django 3.0.3 on 2020-11-17 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0027_auto_20201117_1235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemviewed',
            name='is_viewed',
            field=models.BooleanField(default=False),
        ),
    ]
