# Generated by Django 3.0.3 on 2020-11-09 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0027_auto_20201109_1113'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecturecontent',
            name='file',
            field=models.FileField(blank=True, max_length=500, null=True, upload_to='programs/courses/contents/materials/'),
        ),
    ]
