# Generated by Django 3.0.3 on 2020-11-01 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0027_auto_20201101_1158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseblock',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
