# Generated by Django 3.0.3 on 2020-11-07 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0027_auto_20201107_0916'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lecturecontent',
            name='name',
        ),
    ]
