# Generated by Django 3.0.3 on 2020-11-15 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0027_auto_20201114_0719'),
    ]

    operations = [
        migrations.RenameField(
            model_name='itemquestion',
            old_name='question',
            new_name='details',
        ),
    ]
