# Generated by Django 3.0.3 on 2020-11-18 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0027_auto_20201118_1353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecturecontent',
            name='name',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
