# Generated by Django 3.0.3 on 2020-11-01 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0028_auto_20201101_1516'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='activated',
            field=models.BooleanField(default=False),
        ),
    ]
