# Generated by Django 3.0.3 on 2020-11-09 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0028_lecturecontent_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecturecontent',
            name='type_choices',
            field=models.CharField(choices=[('VI', 'Video'), ('TX', 'Text'), ('MA', 'Material')], max_length=2),
        ),
    ]
