# Generated by Django 3.0.3 on 2020-11-16 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0028_auto_20201115_1701'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['created']},
        ),
        migrations.AlterModelOptions(
            name='itemanswer',
            options={'ordering': ['created']},
        ),
        migrations.AddField(
            model_name='course',
            name='color',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='itemviewed',
            name='duration',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
