# Generated by Django 3.0.3 on 2020-11-07 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0029_lecturecontent_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecturecontent',
            name='name',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
