# Generated by Django 3.0.3 on 2020-11-01 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0029_course_activated'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='activated',
            new_name='published_in_program',
        ),
    ]
