# Generated by Django 3.0.3 on 2020-11-02 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0030_auto_20201101_1528'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='name',
        ),
        migrations.AddField(
            model_name='course',
            name='subtitle',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='title',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
