# Generated by Django 3.0.3 on 2020-12-12 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0030_courseitem_is_free'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='offer_persentage',
            field=models.IntegerField(default=0),
        ),
    ]
