# Generated by Django 3.0.3 on 2020-11-03 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0031_auto_20201102_0935'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courseblocktrack',
            name='code',
        ),
        migrations.RemoveField(
            model_name='courseitemtrack',
            name='code',
        ),
        migrations.AddField(
            model_name='course',
            name='blocks',
            field=models.ManyToManyField(through='programs.CourseBlockTrack', to='programs.CourseBlock'),
        ),
    ]
