// Auth
export const USER_LOADING = "USER_LOADING";
export const USER_LOADED = "USER_LOADED";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const AUTH_ERROR = "AUTH_ERROR";
export const UPDATE_PROFILE = "UPDATE_PROFILE";
export const UPDATE_PROFILE_SUCCESS = "UPDATE_PROFILE_SUCCESS";
export const UPDATE_PROFILE_FAIL = "UPDATE_PROFILE_FAIL";
export const UPDATE_USER = "UPDATE_USER";
export const UPDATE_USER_SUCCESS = "UPDATE_USER_SUCCESS";
export const UPDATE_USER_FAIL = "UPDATE_USER_FAIL";
export const CHANGE_PASSWORD = "CHANGE_PASSWORD";
export const CHANGE_PASSWORD_SUCCESS = "CHANGE_PASSWORD_SUCCESS";
export const CHANGE_PASSWORD_FAIL = "CHANGE_PASSWORD_FAIL";
export const STRIPE_CONNECTED = "STRIPE_CONNECTED";
export const STRIPE_CONNECTED_SUCCESS = "STRIPE_CONNECTED_SUCCESS";
export const STRIPE_CONNECTED_FAIL = "STRIPE_CONNECTED_FAIL";

// Program
export const PROGRAM_FETCH = "PROGRAM_FETCH";
export const PROGRAM_SUCCESS = "PROGRAM_LOADED";
export const PROGRAM_FAIL = "PROGRAM_FAIL";
export const PROGRAM_PICTURE_UPLOAD = "PROGRAM_PICTURE_UPLOAD";
export const PROGRAM_PICTURE_SUCCESS = "PROGRAM_PICTURE_SUCCESS";
export const PROGRAM_PICTURE_FAIL = "PROGRAM_PICTURE_FAIL";
export const PROGRAM_SAVE = "PROGRAM_SAVE";
export const PROGRAM_SAVE_SUCCESS = "PROGRAM_SAVE_SUCCESS";
export const PROGRAM_SAVE_FAIL = "PROGRAM_SAVE_FAIL";
export const PROGRAM_VIDEO_UPLOAD = "PROGRAM_VIDEO_UPLOAD";
export const PROGRAM_VIDEO_SUCCESS = "PROGRAM_VIDEO_SUCCESS";
export const PROGRAM_VIDEO_FAIL = "PROGRAM_VIDEO_FAIL";
export const PROGRAM_ACTIVE = "PROGRAM_ACTIVE";
export const PROGRAM_ACTIVE_SUCCESS = "PROGRAM_ACTIVE_SUCCESS";
export const PROGRAM_ACTIVE_FAIL = "PROGRAM_ACTIVE_FAIL";
export const PROGRAM_CANCEL_ACTIVE = "PROGRAM_CANCEL_ACTIVE";
export const PROGRAM_CANCEL_ACTIVE_SUCCESS = "PROGRAM_CANCEL_ACTIVE_SUCCESS";
export const PROGRAM_CANCEL_ACTIVE_FAIL = "PROGRAM_CANCEL_ACTIVE_FAIL";
export const PROGRAM_PUBLISH = "PROGRAM_PUBLISH";
export const PROGRAM_PUBLISH_SUCCESS = "PROGRAM_PUBLISH_SUCCESS";
export const PROGRAM_PUBLISH_FAIL = "PROGRAM_PUBLISH_FAIL";
export const PROGRAM_CANCEL_PUBLISH = "PROGRAM_CANCEL_PUBLISH";
export const PROGRAM_CANCEL_PUBLISH_SUCCESS = "PROGRAM_CANCEL_PUBLISH_SUCCESS";
export const PROGRAM_CANCEL_PUBLISH_FAIL = "PROGRAM_CANCEL_PUBLISH_FAIL";
export const REMOVE_PROGRAM = "REMOVE_PROGRAM";
export const REMOVE_PROGRAM_SUCCESS = "REMOVE_PROGRAM_SUCCESS";
export const REMOVE_PROGRAM_FAIL = "REMOVE_PROGRAM_FAIL";
export const ACQUIRE_ACCOUNTS = "ACQUIRE_ACCOUNTS";
export const ACQUIRE_ACCOUNTS_SUCCESS = "ACQUIRE_ACCOUNTS_SUCCESS";
export const ACQUIRE_ACCOUNTS_FAIL = "ACQUIRE_ACCOUNTS_FAIL";
export const CANECEL_ACCOUNTS = "CANECEL_ACCOUNTS";
export const CANECEL_ACCOUNTS_SUCCESS = "CANECEL_ACCOUNTS_SUCCESS";
export const CANECEL_ACCOUNTS_FAIL = "CANECEL_ACCOUNTS_FAIL";
export const SET_STRIPE_CUSTOMER_DATA = "SET_STRIPE_CUSTOMER_DATA";
export const SET_TEACHER_DISCOUNT = "SET_TEACHER_DISCOUNT";
export const REMOVE_TEACHER_DISCOUNT = "REMOVE_TEACHER_DISCOUNT";

export const REFRESH_PROGRAM = "REFRESH_PROGRAM";
export const CREATE_RATING = "CREATE_RATING";
export const CREATE_RATING_SUCCESS = "CREATE_RATING_SUCCESS";
export const CREATE_RATING_FAIL = "CREATE_RATING_FAIL";

// Popular Videos
export const POPULAR_VIDEOS_FETCH = "POPULAR_VIDEOS_FETCH";
export const POPULAR_VIDEOS_SUCCESS = "POPULAR_VIDEOS_SUCCESS";
export const POPULAR_VIDEOS_FAIL = "POPULAR_VIDEOS_FAIL";

// Popular Playlists
export const POPULAR_PLAYLISTS_FETCH = "POPULAR_PLAYLISTS_FETCH";
export const POPULAR_PLAYLISTS_SUCCESS = "POPULAR_PLAYLISTS_SUCCESS";
export const POPULAR_PLAYLISTS_FAIL = "POPULAR_PLAYLISTS_FAIL";

// Popular Podcasts
export const POPULAR_PODCASTS_FETCH = "POPULAR_PODCASTS_FETCH";
export const POPULAR_PODCASTS_SUCCESS = "POPULAR_PODCASTS_SUCCESS";
export const POPULAR_PODCASTS_FAIL = "POPULAR_PODCASTS_FAIL";

// Videos
export const VIDEOS_FETCH = "VIDEOS_FETCH";
export const VIDEOS_SUCCESS = "VIDEOS_LOADED";
export const VIDEOS_FAIL = "VIDEOS_FAIL";
export const SET_VIDEO_EDIT = "SET_VIDEO_EDIT";
export const DELETE_VIDEO_EDIT = "DELETE_VIDEO_EDIT";
export const EDIT_VIDEO = "EDIT_VIDEO";
export const EDIT_VIDEO_SUCCESS = "EDIT_VIDEO_SUCCESS";
export const EDIT_VIDEO_FAIL = "EDIT_VIDEO_FAIL";
export const CREATE_VIDEO = "CREATE_VIDEO";
export const CREATE_VIDEO_SUCCESS = "CREATE_VIDEO_SUCCESS";
export const CREATE_VIDEO_FAIL = "CREATE_VIDEO_FAIL";
export const DELETE_VIDEO = "DELETE_VIDEO";
export const DELETE_VIDEO_SUCCESS = "DELETE_VIDEO_SUCCESS";
export const DELETE_VIDEO_FAIL = "DELETE_VIDEO_FAIL";

// Video
export const VIDEO_FETCH = "VIDEO_FETCH";
export const VIDEO_SUCCESS = "VIDEO_LOADED";
export const VIDEO_FAIL = "VIDEO_FAIL";

// Recomended Videos
export const RECOMENDED_VIDEOS_FETCH = "RECOMENDED_VIDEOS_FETCH";
export const RECOMENDED_VIDEOS_SUCCESS = "RECOMENDED_VIDEOS_SUCCESS";
export const RECOMENDED_VIDEOS_FAIL = "RECOMENDED_VIDEOS_FAIL";

// Playlists
export const PLAYLISTS_FETCH = "PLAYLISTS_FETCH";
export const PLAYLISTS_SUCCESS = "PLAYLISTS_LOADED";
export const PLAYLISTS_FAIL = "PLAYLISTS_FAIL";
export const SET_PLAYLIST_EDIT = "SET_PLAYLIST_EDIT";
export const DELETE_PLAYLIST_EDIT = "DELETE_PLAYLIST_EDIT";
export const EDIT_PLAYLIST = "EDIT_PLAYLIST";
export const EDIT_PLAYLIST_SUCCESS = "EDIT_PLAYLIST_SUCCESS";
export const EDIT_PLAYLIST_FAIL = "EDIT_PLAYLIST_FAIL";
export const CREATE_PLAYLIST = "CREATE_PLAYLIST";
export const CREATE_PLAYLIST_SUCCESS = "CREATE_PLAYLIST_SUCCESS";
export const CREATE_PLAYLIST_FAIL = "CREATE_PLAYLIST_FAIL";
export const DELETE_PLAYLIST = "DELETE_PLAYLIST";
export const DELETE_PLAYLIST_SUCCESS = "DELETE_PLAYLIST_SUCCESS";
export const DELETE_PLAYLIST_FAIL = "DELETE_PLAYLIST_FAIL";

// Playlist
export const PLAYLIST_FETCH = "PLAYLIST_FETCH";
export const PLAYLIST_SUCCESS = "PLAYLIST_LOADED";
export const PLAYLIST_FAIL = "PLAYLIST_FAIL";

// Podcasts
export const PODCASTS_FETCH = "PODCASTS_FETCH";
export const PODCASTS_SUCCESS = "PODCASTS_LOADED";
export const PODCASTS_FAIL = "PODCASTS_FAIL";
export const PLAY_PODCAST = "PLAY_PODCAST";
export const STOP_PODCAST = "STOP_PODCAST";
export const SET_PODCAST_EDIT = "SET_PODCAST_EDIT";
export const DELETE_PODCAST_EDIT = "DELETE_PODCAST_EDIT";
export const EDIT_PODCAST = "EDIT_PODCAST";
export const EDIT_PODCAST_SUCCESS = "EDIT_PODCAST_SUCCESS";
export const EDIT_PODCAST_FAIL = "EDIT_PODCAST_FAIL";
export const CREATE_PODCAST = "CREATE_PODCAST";
export const CREATE_PODCAST_SUCCESS = "CREATE_PODCAST_SUCCESS";
export const CREATE_PODCAST_FAIL = "CREATE_PODCAST_FAIL";
export const DELETE_PODCAST = "DELETE_PODCAST";
export const DELETE_PODCAST_SUCCESS = "DELETE_PODCAST_SUCCESS";
export const DELETE_PODCAST_FAIL = "DELETE_PODCAST_FAIL";

// Meetups
export const MEETUPS_FETCH = "MEETUPS_FETCH";
export const MEETUPS_SUCCESS = "MEETUPS_LOADED";
export const MEETUPS_FAIL = "MEETUPS_FAIL";
export const CREATE_MEETUP = "CREATE_MEETUP";
export const CREATE_MEETUP_SUCCESS = "CREATE_MEETUP_SUCCESS";
export const CREATE_MEETUP_FAIL = "CREATE_MEETUP_FAIL";
export const EDIT_MEETUP = "EDIT_MEETUP";
export const EDIT_MEETUP_SUCCESS = "EDIT_MEETUP_SUCCESS";
export const EDIT_MEETUP_FAIL = "EDIT_MEETUP_FAIL";
export const DELETE_MEETUP = "DELETE_MEETUP";
export const DELETE_MEETUP_SUCCESS = "DELETE_MEETUP_SUCCESS";
export const DELETE_MEETUP_FAIL = "DELETE_MEETUP_FAIL";

// Students
export const STUDENTS_FETCH = "STUDENTS_FETCH";
export const STUDENTS_SUCCESS = "STUDENTS_LOADED";
export const STUDENTS_FAIL = "STUDENTS_FAIL";

// Counts created
export const ACCOUNTS_FETCH = "ACCOUNTS_FETCH";
export const ACCOUNTS_SUCCESS = "ACCOUNTS_SUCCESS";
export const ACCOUNTS_FAIL = "ACCOUNTS_FAIL";
export const CREATE_ACCOUNT = "CREATE_ACCOUNT";
export const CREATE_ACCOUNT_SUCCESS = "CREATE_ACCOUNT_SUCCESS";
export const CREATE_ACCOUNT_FAIL = "CREATE_ACCOUNT_FAIL";
export const DELETE_ACCOUNT = "DELETE_ACCOUNT";
export const DELETE_ACCOUNT_SUCCESS = "DELETE_ACCOUNT_SUCCESS";
export const DELETE_ACCOUNT_FAIL = "DELETE_ACCOUNT_FAIL";
export const RESET_ACCOUNT_CREATE = "RESET_ACCOUNT_CREATE";

// Students
export const PRICING_FETCH = "PRICING_FETCH";
export const PRICING_SUCCESS = "PRICING_LOADED";
export const PRICING_FAIL = "PRICING_FAIL";

// Commercials

// Auth Commercials
export const COMMERCIAL_LOADING = "COMMERCIAL_LOADING";
export const COMMERCIAL_LOADED = "COMMERCIAL_LOADED";
export const LOGIN_COMMERCIAL_SUCCESS = "LOGIN_COMMERCIAL_SUCCESS";
export const LOGOUT_COMMERCIAL_SUCCESS = "LOGOUT_COMMERCIAL_SUCCESS";
export const LOGIN_COMMERCIAL_FAIL = "LOGIN_COMMERCIAL_FAIL";
export const AUTH_COMMERCIAL_ERROR = "AUTH_COMMERCIAL_ERROR";
export const UPDATE_COMMERCIAL_PROFILE = "UPDATE_COMMERCIAL_PROFILE";
export const UPDATE_COMMERCIAL_PROFILE_SUCCESS =
  "UPDATE_COMMERCIAL_PROFILE_SUCCESS";
export const UPDATE_COMMERCIAL_PROFILE_FAIL = "UPDATE_COMMERCIAL_PROFILE_FAIL";
export const UPDATE_COMMERCIAL = "UPDATE_COMMERCIAL";
export const UPDATE_COMMERCIAL_SUCCESS = "UPDATE_COMMERCIAL_SUCCESS";
export const UPDATE_COMMERCIAL_FAIL = "UPDATE_COMMERCIAL_FAIL";
export const CHANGE_COMMERCIAL_PASSWORD = "CHANGE_COMMERCIAL_PASSWORD";
export const CHANGE_COMMERCIAL_PASSWORD_SUCCESS =
  "CHANGE_COMMERCIAL_PASSWORD_SUCCESS";
export const CHANGE_COMMERCIAL_PASSWORD_FAIL =
  "CHANGE_COMMERCIAL_PASSWORD_FAIL";
export const STRIPE_COMMERCIAL_CONNECTED = "STRIPE_COMMERCIAL_CONNECTED";
export const STRIPE_COMMERCIAL_CONNECTED_SUCCESS =
  "STRIPE_COMMERCIAL_CONNECTED_SUCCESS";
export const STRIPE_COMMERCIAL_CONNECTED_FAIL =
  "STRIPE_COMMERCIAL_CONNECTED_FAIL";
