// Auth
export const USER_LOADING = "USER_LOADING";
export const USER_LOADED = "USER_LOADED";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const AUTH_ERROR = "AUTH_ERROR";
export const UPDATE_PROFILE = "UPDATE_PROFILE";
export const UPDATE_PROFILE_SUCCESS = "UPDATE_PROFILE_SUCCESS";
export const UPDATE_PROFILE_FAIL = "UPDATE_PROFILE_FAIL";
export const UPDATE_USER = "UPDATE_USER";
export const UPDATE_USER_SUCCESS = "UPDATE_USER_SUCCESS";
export const UPDATE_USER_FAIL = "UPDATE_USER_FAIL";
export const CHANGE_PASSWORD = "CHANGE_PASSWORD";
export const CHANGE_PASSWORD_SUCCESS = "CHANGE_PASSWORD_SUCCESS";
export const CHANGE_PASSWORD_FAIL = "CHANGE_PASSWORD_FAIL";
export const STRIPE_CONNECTED = "STRIPE_CONNECTED";
export const STRIPE_CONNECTED_SUCCESS = "STRIPE_CONNECTED_SUCCESS";
export const STRIPE_CONNECTED_FAIL = "STRIPE_CONNECTED_FAIL";
export const SET_IS_INSTRUCTOR = "SET_IS_INSTRUCTOR";

// Program
export const PROGRAM_FETCH = "PROGRAM_FETCH";
export const PROGRAM_SUCCESS = "PROGRAM_LOADED";
export const PROGRAM_FAIL = "PROGRAM_FAIL";
export const PROGRAM_PICTURE_UPLOAD = "PROGRAM_PICTURE_UPLOAD";
export const PROGRAM_PICTURE_SUCCESS = "PROGRAM_PICTURE_SUCCESS";
export const PROGRAM_PICTURE_FAIL = "PROGRAM_PICTURE_FAIL";
export const PROGRAM_SAVE = "PROGRAM_SAVE";
export const PROGRAM_SAVE_SUCCESS = "PROGRAM_SAVE_SUCCESS";
export const PROGRAM_SAVE_FAIL = "PROGRAM_SAVE_FAIL";
export const PROGRAM_VIDEO_UPLOAD = "PROGRAM_VIDEO_UPLOAD";
export const PROGRAM_VIDEO_SUCCESS = "PROGRAM_VIDEO_SUCCESS";
export const PROGRAM_VIDEO_FAIL = "PROGRAM_VIDEO_FAIL";
export const PROGRAM_ACTIVE = "PROGRAM_ACTIVE";
export const PROGRAM_ACTIVE_SUCCESS = "PROGRAM_ACTIVE_SUCCESS";
export const PROGRAM_ACTIVE_FAIL = "PROGRAM_ACTIVE_FAIL";
export const PROGRAM_CANCEL_ACTIVE = "PROGRAM_CANCEL_ACTIVE";
export const PROGRAM_CANCEL_ACTIVE_SUCCESS = "PROGRAM_CANCEL_ACTIVE_SUCCESS";
export const PROGRAM_CANCEL_ACTIVE_FAIL = "PROGRAM_CANCEL_ACTIVE_FAIL";
export const PROGRAM_PUBLISH = "PROGRAM_PUBLISH";
export const PROGRAM_PUBLISH_SUCCESS = "PROGRAM_PUBLISH_SUCCESS";
export const PROGRAM_PUBLISH_FAIL = "PROGRAM_PUBLISH_FAIL";
export const PROGRAM_CANCEL_PUBLISH = "PROGRAM_CANCEL_PUBLISH";
export const PROGRAM_CANCEL_PUBLISH_SUCCESS = "PROGRAM_CANCEL_PUBLISH_SUCCESS";
export const PROGRAM_CANCEL_PUBLISH_FAIL = "PROGRAM_CANCEL_PUBLISH_FAIL";
export const REMOVE_PROGRAM = "REMOVE_PROGRAM";
export const REMOVE_PROGRAM_SUCCESS = "REMOVE_PROGRAM_SUCCESS";
export const REMOVE_PROGRAM_FAIL = "REMOVE_PROGRAM_FAIL";
export const ACQUIRE_ACCOUNTS = "ACQUIRE_ACCOUNTS";
export const ACQUIRE_ACCOUNTS_SUCCESS = "ACQUIRE_ACCOUNTS_SUCCESS";
export const ACQUIRE_ACCOUNTS_FAIL = "ACQUIRE_ACCOUNTS_FAIL";
export const CANECEL_ACCOUNTS = "CANECEL_ACCOUNTS";
export const CANECEL_ACCOUNTS_SUCCESS = "CANECEL_ACCOUNTS_SUCCESS";
export const CANECEL_ACCOUNTS_FAIL = "CANECEL_ACCOUNTS_FAIL";
export const SET_STRIPE_CUSTOMER_DATA = "SET_STRIPE_CUSTOMER_DATA";
export const SET_TEACHER_DISCOUNT = "SET_TEACHER_DISCOUNT";
export const REMOVE_TEACHER_DISCOUNT = "REMOVE_TEACHER_DISCOUNT";
export const ACTIVE_BOOKING = "ACTIVE_BOOKING";
export const ACTIVE_BOOKING_SUCCESS = "ACTIVE_BOOKING_SUCCESS";
export const ACTIVE_BOOKING_FAIL = "ACTIVE_BOOKING_FAIL";
export const CANCEL_BOOKING = "CANCEL_BOOKING";
export const CANCEL_BOOKING_SUCCESS = "CANCEL_BOOKING_SUCCESS";
export const CANCEL_BOOKING_FAIL = "CANCEL_BOOKING_FAIL";

export const REFRESH_PROGRAM = "REFRESH_PROGRAM";
export const CREATE_RATING = "CREATE_RATING";
export const CREATE_RATING_SUCCESS = "CREATE_RATING_SUCCESS";
export const CREATE_RATING_FAIL = "CREATE_RATING_FAIL";

// Popular Videos
export const POPULAR_VIDEOS_FETCH = "POPULAR_VIDEOS_FETCH";
export const POPULAR_VIDEOS_SUCCESS = "POPULAR_VIDEOS_SUCCESS";
export const POPULAR_VIDEOS_FAIL = "POPULAR_VIDEOS_FAIL";

// Popular Playlists
export const POPULAR_PLAYLISTS_FETCH = "POPULAR_PLAYLISTS_FETCH";
export const POPULAR_PLAYLISTS_SUCCESS = "POPULAR_PLAYLISTS_SUCCESS";
export const POPULAR_PLAYLISTS_FAIL = "POPULAR_PLAYLISTS_FAIL";

// Popular Podcasts
export const POPULAR_PODCASTS_FETCH = "POPULAR_PODCASTS_FETCH";
export const POPULAR_PODCASTS_SUCCESS = "POPULAR_PODCASTS_SUCCESS";
export const POPULAR_PODCASTS_FAIL = "POPULAR_PODCASTS_FAIL";

// Videos
export const VIDEOS_FETCH = "VIDEOS_FETCH";
export const VIDEOS_SUCCESS = "VIDEOS_LOADED";
export const VIDEOS_FAIL = "VIDEOS_FAIL";
export const SET_VIDEO_EDIT = "SET_VIDEO_EDIT";
export const DELETE_VIDEO_EDIT = "DELETE_VIDEO_EDIT";
export const EDIT_VIDEO = "EDIT_VIDEO";
export const EDIT_VIDEO_SUCCESS = "EDIT_VIDEO_SUCCESS";
export const EDIT_VIDEO_FAIL = "EDIT_VIDEO_FAIL";
export const CREATE_VIDEO = "CREATE_VIDEO";
export const CREATE_VIDEO_SUCCESS = "CREATE_VIDEO_SUCCESS";
export const CREATE_VIDEO_FAIL = "CREATE_VIDEO_FAIL";
export const DELETE_VIDEO = "DELETE_VIDEO";
export const DELETE_VIDEO_SUCCESS = "DELETE_VIDEO_SUCCESS";
export const DELETE_VIDEO_FAIL = "DELETE_VIDEO_FAIL";

// Video
export const VIDEO_FETCH = "VIDEO_FETCH";
export const VIDEO_SUCCESS = "VIDEO_LOADED";
export const VIDEO_FAIL = "VIDEO_FAIL";

// Recomended Videos
export const RECOMENDED_VIDEOS_FETCH = "RECOMENDED_VIDEOS_FETCH";
export const RECOMENDED_VIDEOS_SUCCESS = "RECOMENDED_VIDEOS_SUCCESS";
export const RECOMENDED_VIDEOS_FAIL = "RECOMENDED_VIDEOS_FAIL";

// Playlists
export const PLAYLISTS_FETCH = "PLAYLISTS_FETCH";
export const PLAYLISTS_SUCCESS = "PLAYLISTS_LOADED";
export const PLAYLISTS_FAIL = "PLAYLISTS_FAIL";
export const SET_PLAYLIST_EDIT = "SET_PLAYLIST_EDIT";
export const DELETE_PLAYLIST_EDIT = "DELETE_PLAYLIST_EDIT";
export const EDIT_PLAYLIST = "EDIT_PLAYLIST";
export const EDIT_PLAYLIST_SUCCESS = "EDIT_PLAYLIST_SUCCESS";
export const EDIT_PLAYLIST_FAIL = "EDIT_PLAYLIST_FAIL";
export const CREATE_PLAYLIST = "CREATE_PLAYLIST";
export const CREATE_PLAYLIST_SUCCESS = "CREATE_PLAYLIST_SUCCESS";
export const CREATE_PLAYLIST_FAIL = "CREATE_PLAYLIST_FAIL";
export const DELETE_PLAYLIST = "DELETE_PLAYLIST";
export const DELETE_PLAYLIST_SUCCESS = "DELETE_PLAYLIST_SUCCESS";
export const DELETE_PLAYLIST_FAIL = "DELETE_PLAYLIST_FAIL";

// Playlist
export const PLAYLIST_FETCH = "PLAYLIST_FETCH";
export const PLAYLIST_SUCCESS = "PLAYLIST_SUCCESS";
export const PLAYLIST_FAIL = "PLAYLIST_FAIL";

// Courses
export const COURSES_FETCH = "COURSES_FETCH";
export const COURSES_SUCCESS = "COURSES_SUCCESS";
export const COURSES_FAIL = "COURSES_FAIL";
export const SET_COURSE_EDIT = "SET_COURSE_EDIT";
export const DELETE_COURSE_EDIT = "DELETE_COURSE_EDIT";
export const EDIT_COURSE = "EDIT_COURSE";
export const EDIT_COURSE_SUCCESS = "EDIT_COURSE_SUCCESS";
export const EDIT_COURSE_FAIL = "EDIT_COURSE_FAIL";
export const CREATE_COURSE = "CREATE_COURSE";
export const CREATE_COURSE_SUCCESS = "CREATE_COURSE_SUCCESS";
export const CREATE_COURSE_FAIL = "CREATE_COURSE_FAIL";
export const DELETE_COURSE = "DELETE_COURSE";
export const DELETE_COURSE_SUCCESS = "DELETE_COURSE_SUCCESS";
export const DELETE_COURSE_FAIL = "DELETE_COURSE_FAIL";

// Course
export const COURSE_FETCH = "COURSE_FETCH";
export const COURSE_SUCCESS = "COURSE_SUCCESS";
export const COURSE_FAIL = "COURSE_FAIL";

// Podcasts
export const PODCASTS_FETCH = "PODCASTS_FETCH";
export const PODCASTS_SUCCESS = "PODCASTS_LOADED";
export const PODCASTS_FAIL = "PODCASTS_FAIL";
export const PLAY_PODCAST = "PLAY_PODCAST";
export const STOP_PODCAST = "STOP_PODCAST";
export const SET_PODCAST_EDIT = "SET_PODCAST_EDIT";
export const DELETE_PODCAST_EDIT = "DELETE_PODCAST_EDIT";
export const EDIT_PODCAST = "EDIT_PODCAST";
export const EDIT_PODCAST_SUCCESS = "EDIT_PODCAST_SUCCESS";
export const EDIT_PODCAST_FAIL = "EDIT_PODCAST_FAIL";
export const CREATE_PODCAST = "CREATE_PODCAST";
export const CREATE_PODCAST_SUCCESS = "CREATE_PODCAST_SUCCESS";
export const CREATE_PODCAST_FAIL = "CREATE_PODCAST_FAIL";
export const DELETE_PODCAST = "DELETE_PODCAST";
export const DELETE_PODCAST_SUCCESS = "DELETE_PODCAST_SUCCESS";
export const DELETE_PODCAST_FAIL = "DELETE_PODCAST_FAIL";

// Meetups
export const MEETUPS_FETCH = "MEETUPS_FETCH";
export const MEETUPS_SUCCESS = "MEETUPS_LOADED";
export const MEETUPS_FAIL = "MEETUPS_FAIL";
export const CREATE_MEETUP = "CREATE_MEETUP";
export const CREATE_MEETUP_SUCCESS = "CREATE_MEETUP_SUCCESS";
export const CREATE_MEETUP_FAIL = "CREATE_MEETUP_FAIL";
export const EDIT_MEETUP = "EDIT_MEETUP";
export const EDIT_MEETUP_SUCCESS = "EDIT_MEETUP_SUCCESS";
export const EDIT_MEETUP_FAIL = "EDIT_MEETUP_FAIL";
export const DELETE_MEETUP = "DELETE_MEETUP";
export const DELETE_MEETUP_SUCCESS = "DELETE_MEETUP_SUCCESS";
export const DELETE_MEETUP_FAIL = "DELETE_MEETUP_FAIL";

// Students
export const STUDENTS_FETCH = "STUDENTS_FETCH";
export const STUDENTS_SUCCESS = "STUDENTS_LOADED";
export const STUDENTS_FAIL = "STUDENTS_FAIL";

// Counts created
export const ACCOUNTS_FETCH = "ACCOUNTS_FETCH";
export const ACCOUNTS_SUCCESS = "ACCOUNTS_SUCCESS";
export const ACCOUNTS_FAIL = "ACCOUNTS_FAIL";
export const CREATE_ACCOUNT = "CREATE_ACCOUNT";
export const CREATE_ACCOUNT_SUCCESS = "CREATE_ACCOUNT_SUCCESS";
export const CREATE_ACCOUNT_FAIL = "CREATE_ACCOUNT_FAIL";
export const DELETE_ACCOUNT = "DELETE_ACCOUNT";
export const DELETE_ACCOUNT_SUCCESS = "DELETE_ACCOUNT_SUCCESS";
export const DELETE_ACCOUNT_FAIL = "DELETE_ACCOUNT_FAIL";
export const RESET_ACCOUNT_CREATE = "RESET_ACCOUNT_CREATE";

// Pricing
export const PRICING_FETCH = "PRICING_FETCH";
export const PRICING_SUCCESS = "PRICING_LOADED";
export const PRICING_FAIL = "PRICING_FAIL";

// Commercials

// Auth Commercials
export const COMMERCIAL_LOADING = "COMMERCIAL_LOADING";
export const COMMERCIAL_LOADED = "COMMERCIAL_LOADED";
export const LOGIN_COMMERCIAL_SUCCESS = "LOGIN_COMMERCIAL_SUCCESS";
export const LOGOUT_COMMERCIAL_SUCCESS = "LOGOUT_COMMERCIAL_SUCCESS";
export const LOGIN_COMMERCIAL_FAIL = "LOGIN_COMMERCIAL_FAIL";
export const AUTH_COMMERCIAL_ERROR = "AUTH_COMMERCIAL_ERROR";
export const UPDATE_COMMERCIAL_PROFILE = "UPDATE_COMMERCIAL_PROFILE";
export const UPDATE_COMMERCIAL_PROFILE_SUCCESS =
  "UPDATE_COMMERCIAL_PROFILE_SUCCESS";
export const UPDATE_COMMERCIAL_PROFILE_FAIL = "UPDATE_COMMERCIAL_PROFILE_FAIL";
export const UPDATE_COMMERCIAL = "UPDATE_COMMERCIAL";
export const UPDATE_COMMERCIAL_SUCCESS = "UPDATE_COMMERCIAL_SUCCESS";
export const UPDATE_COMMERCIAL_FAIL = "UPDATE_COMMERCIAL_FAIL";
export const CHANGE_COMMERCIAL_PASSWORD = "CHANGE_COMMERCIAL_PASSWORD";
export const CHANGE_COMMERCIAL_PASSWORD_SUCCESS =
  "CHANGE_COMMERCIAL_PASSWORD_SUCCESS";
export const CHANGE_COMMERCIAL_PASSWORD_FAIL =
  "CHANGE_COMMERCIAL_PASSWORD_FAIL";
export const STRIPE_COMMERCIAL_CONNECTED = "STRIPE_COMMERCIAL_CONNECTED";
export const STRIPE_COMMERCIAL_CONNECTED_SUCCESS =
  "STRIPE_COMMERCIAL_CONNECTED_SUCCESS";
export const STRIPE_COMMERCIAL_CONNECTED_FAIL =
  "STRIPE_COMMERCIAL_CONNECTED_FAIL";
export const RESET_AUTH_ERRORS = "RESET_AUTH_ERRORS";
export const REGISTER_WITH_TOKEN_SUCCESS = "REGISTER_WITH_TOKEN_SUCCESS";

// Costumers created by commercial
export const COSTUMERS_FETCH = "COSTUMERS_FETCH";
export const COSTUMERS_SUCCESS = "COSTUMERS_SUCCESS";
export const COSTUMERS_FAIL = "COSTUMERS_FAIL";
export const CREATE_COSTUMER = "CREATE_COSTUMER";
export const CREATE_COSTUMER_SUCCESS = "CREATE_COSTUMER_SUCCESS";
export const CREATE_COSTUMER_FAIL = "CREATE_COSTUMER_FAIL";
export const DELETE_COSTUMER = "DELETE_COSTUMER";
export const DELETE_COSTUMER_SUCCESS = "DELETE_COSTUMER_SUCCESS";
export const DELETE_COSTUMER_FAIL = "DELETE_COSTUMER_FAIL";
export const RESET_COSTUMER_CREATE = "RESET_COSTUMER_CREATE";

// Commercials created by commercial
export const COMMERCIALS_FETCH = "COMMERCIALS_FETCH";
export const COMMERCIALS_SUCCESS = "COMMERCIALS_SUCCESS";
export const COMMERCIALS_FAIL = "COMMERCIALS_FAIL";
export const CREATE_COMMERCIAL = "CREATE_COMMERCIAL";
export const CREATE_COMMERCIAL_SUCCESS = "CREATE_COMMERCIAL_SUCCESS";
export const CREATE_COMMERCIAL_FAIL = "CREATE_COMMERCIAL_FAIL";
export const DELETE_COMMERCIAL = "DELETE_COMMERCIAL";
export const DELETE_COMMERCIAL_SUCCESS = "DELETE_COMMERCIAL_SUCCESS";
export const DELETE_COMMERCIAL_FAIL = "DELETE_COMMERCIAL_FAIL";
export const RESET_COMMERCIAL_CREATE = "RESET_COMMERCIAL_CREATE";
export const CHANGE_CURRENT_COMMERCIAL = "CHANGE_CURRENT_COMMERCIAL";

// Payments

export const PAYMENTS_FETCH = "PAYMENTS_FETCH";
export const PAYMENTS_SUCCESS = "PAYMENTS_SUCCESS";
export const PAYMENTS_FAIL = "PAYMENTS_FAIL";

// Folders
export const FOLDERS_FETCH = "FOLDERS_FETCH";
export const FOLDERS_SUCCESS = "FOLDERS_SUCCESS";
export const FOLDERS_FAIL = "FOLDERS_FAIL";
export const EDIT_FOLDER = "EDIT_FOLDER";
export const EDIT_FOLDER_SUCCESS = "EDIT_FOLDER_SUCCESS";
export const EDIT_FOLDER_FAIL = "EDIT_FOLDER_FAIL";
export const CREATE_FOLDER = "CREATE_FOLDER";
export const CREATE_FOLDER_SUCCESS = "CREATE_FOLDER_SUCCESS";
export const CREATE_FOLDER_FAIL = "CREATE_FOLDER_FAIL";
export const DELETE_FOLDER = "DELETE_FOLDER";
export const DELETE_FOLDER_SUCCESS = "DELETE_FOLDER_SUCCESS";
export const DELETE_FOLDER_FAIL = "DELETE_FOLDER_FAIL";
export const SET_CURRENT_FOLDER = "SET_CURRENT_FOLDER";
export const REMOVE_CURRENT_FOLDER = "REMOVE_CURRENT_FOLDER";

// Files
export const FILES_FETCH = "FILES_FETCH";
export const FILES_SUCCESS = "FILES_SUCCESS";
export const FILES_FAIL = "FILES_FAIL";
export const EDIT_FILE = "EDIT_FILE";
export const EDIT_FILE_SUCCESS = "EDIT_FILE_SUCCESS";
export const EDIT_FILE_FAIL = "EDIT_FILE_FAIL";
export const CREATE_FILE = "CREATE_FILE";
export const CREATE_FILE_SUCCESS = "CREATE_FILE_SUCCESS";
export const CREATE_FILE_FAIL = "CREATE_FILE_FAIL";
export const DELETE_FILE = "DELETE_FILE";
export const DELETE_FILE_SUCCESS = "DELETE_FILE_SUCCESS";
export const DELETE_FILE_FAIL = "DELETE_FILE_FAIL";

// Share students
export const SHARE_STUDENTS_FETCH = "SHARE_STUDENTS_FETCH";
export const SHARE_STUDENTS_SUCCESS = "SHARE_STUDENTS_LOADED";
export const SHARE_STUDENTS_FAIL = "SHARE_STUDENTS_FAIL";

// Folders
export const PUBLIC_FOLDERS_FETCH = "PUBLIC_FOLDERS_FETCH";
export const PUBLIC_FOLDERS_SUCCESS = "PUBLIC_FOLDERS_SUCCESS";
export const PUBLIC_FOLDERS_FAIL = "PUBLIC_FOLDERS_FAIL";
export const SET_CURRENT_PUBLIC_FOLDER = "SET_CURRENT_PUBLIC_FOLDER";
export const REMOVE_CURRENT_PUBLIC_FOLDER = "REMOVE_CURRENT_PUBLIC_FOLDER";

// Files
export const PUBLIC_FILES_FETCH = "PUBLIC_FILES_FETCH";
export const PUBLIC_FILES_SUCCESS = "PUBLIC_FILES_SUCCESS";
export const PUBLIC_FILES_FAIL = "PUBLIC_FILES_FAIL";

// Folders
export const SHARED_FOLDERS_FETCH = "SHARED_FOLDERS_FETCH";
export const SHARED_FOLDERS_SUCCESS = "SHARED_FOLDERS_SUCCESS";
export const SHARED_FOLDERS_FAIL = "SHARED_FOLDERS_FAIL";
export const SET_CURRENT_SHARED_FOLDER = "SET_CURRENT_SHARED_FOLDER";
export const REMOVE_CURRENT_SHARED_FOLDER = "REMOVE_CURRENT_SHARED_FOLDER";

// Files
export const SHARED_FILES_FETCH = "SHARED_FILES_FETCH";
export const SHARED_FILES_SUCCESS = "SHARED_FILES_SUCCESS";
export const SHARED_FILES_FAIL = "SHARED_FILES_FAIL";

// FoldersMove
export const MOVE_FOLDERS_FETCH = "MOVE_FOLDERS_FETCH";
export const MOVE_FOLDERS_SUCCESS = "MOVE_FOLDERS_SUCCESS";
export const MOVE_FOLDERS_FAIL = "MOVE_FOLDERS_FAIL";
export const SET_CURRENT_MOVE_FOLDER = "SET_CURRENT_MOVE_FOLDER";
export const REMOVE_CURRENT_MOVE_FOLDER = "REMOVE_CURRENT_MOVE_FOLDER";

// Files Move
export const MOVE_FILES_FETCH = "MOVE_FILES_FETCH";
export const MOVE_FILES_SUCCESS = "MOVE_FILES_SUCCESS";
export const MOVE_FILES_FAIL = "MOVE_FILES_FAIL";

// Folder Move
export const MOVE_FOLDER = "MOVE_FOLDER";
export const MOVE_FOLDER_SUCCESS = "MOVE_FOLDER_SUCCESS";
export const MOVE_FOLDER_FAIL = "MOVE_FOLDER_FAIL";

// File Move
export const MOVE_FILE = "MOVE_FILE";
export const MOVE_FILE_SUCCESS = "MOVE_FILE_SUCCESS";
export const MOVE_FILE_FAIL = "MOVE_FILE_FAIL";

// Posts

export const POSTS_FETCH = "POSTS_FETCH";
export const POSTS_SUCCESS = "POSTS_SUCCESS";
export const POSTS_FAIL = "POSTS_FAIL";
export const SET_POST_EDIT = "SET_POST_EDIT";
export const DELETE_POST_EDIT = "DELETE_POST_EDIT";
export const EDIT_POST = "EDIT_POST";
export const EDIT_POST_SUCCESS = "EDIT_POST_SUCCESS";
export const EDIT_POST_FAIL = "EDIT_POST_FAIL";
export const CREATE_POST = "CREATE_POST";
export const CREATE_POST_SUCCESS = "CREATE_POST_SUCCESS";
export const CREATE_POST_FAIL = "CREATE_POST_FAIL";
export const DELETE_POST = "DELETE_POST";
export const DELETE_POST_SUCCESS = "DELETE_POST_SUCCESS";
export const DELETE_POST_FAIL = "DELETE_POST_FAIL";

// Post

export const POST_FETCH = "POST_FETCH";
export const POST_SUCCESS = "POST_LOADED";
export const POST_FAIL = "POST_FAIL";
export const INCREASE_COMMENT = "INCREASE_COMMENT";

// Comments

export const COMMENTS_FETCH = "COMMENTS_FETCH";
export const COMMENTS_SUCCESS = "COMMENTS_SUCCESS";
export const COMMENTS_FAIL = "COMMENTS_FAIL";
export const SET_COMMENT_EDIT = "SET_COMMENT_EDIT";
export const DELETE_COMMENT_EDIT = "DELETE_COMMENT_EDIT";
export const EDIT_COMMENT = "EDIT_COMMENT";
export const EDIT_COMMENT_SUCCESS = "EDIT_COMMENT_SUCCESS";
export const EDIT_COMMENT_FAIL = "EDIT_COMMENT_FAIL";
export const CREATE_COMMENT = "CREATE_COMMENT";
export const CREATE_COMMENT_SUCCESS = "CREATE_COMMENT_SUCCESS";
export const CREATE_COMMENT_FAIL = "CREATE_COMMENT_FAIL";
export const DELETE_COMMENT = "DELETE_COMMENT";
export const DELETE_COMMENT_SUCCESS = "DELETE_COMMENT_SUCCESS";
export const DELETE_COMMENT_FAIL = "DELETE_COMMENT_FAIL";

// Instructor Accounts Created
export const INSTRUCTOR_ACCOUNTS_FETCH = "INSTRUCTOR_ACCOUNTS_FETCH";
export const INSTRUCTOR_ACCOUNTS_SUCCESS = "INSTRUCTOR_ACCOUNTS_SUCCESS";
export const INSTRUCTOR_ACCOUNTS_FAIL = "INSTRUCTOR_ACCOUNTS_FAIL";
export const CREATE_INSTRUCTOR_ACCOUNT = "CREATE_INSTRUCTOR_ACCOUNT";
export const CREATE_INSTRUCTOR_ACCOUNT_SUCCESS =
  "CREATE_INSTRUCTOR_ACCOUNT_SUCCESS";
export const CREATE_INSTRUCTOR_ACCOUNT_FAIL = "CREATE_INSTRUCTOR_ACCOUNT_FAIL";
export const DELETE_INSTRUCTOR_ACCOUNT = "DELETE_INSTRUCTOR_ACCOUNT";
export const DELETE_INSTRUCTOR_ACCOUNT_SUCCESS =
  "DELETE_INSTRUCTOR_ACCOUNT_SUCCESS";
export const DELETE_INSTRUCTOR_ACCOUNT_FAIL = "DELETE_INSTRUCTOR_ACCOUNT_FAIL";
export const RESET_INSTRUCTOR_ACCOUNT_CREATE =
  "RESET_INSTRUCTOR_ACCOUNT_CREATE";

export const ADD_ACCOUNT = "ADD_ACCOUNT";
export const SUBSTRACT_ACCOUNT = "SUBSTRACT_ACCOUNT";

export const ACQUIRE_INSTRUCTOR_ACCOUNTS = "ACQUIRE_INSTRUCTOR_ACCOUNTS";
export const ACQUIRE_INSTRUCTOR_ACCOUNTS_SUCCESS =
  "ACQUIRE_INSTRUCTOR_ACCOUNTS_SUCCESS";
export const ACQUIRE_INSTRUCTOR_ACCOUNTS_FAIL =
  "ACQUIRE_INSTRUCTOR_ACCOUNTS_FAIL";
export const CANECEL_INSTRUCTOR_ACCOUNTS = "CANECEL_INSTRUCTOR_ACCOUNTS";
export const CANECEL_INSTRUCTOR_ACCOUNTS_SUCCESS =
  "CANECEL_INSTRUCTOR_ACCOUNTS_SUCCESS";
export const CANECEL_INSTRUCTOR_ACCOUNTS_FAIL =
  "CANECEL_INSTRUCTOR_ACCOUNTS_FAIL";

// Reservar eventos
export const SET_SELECTED_EVENT = "SET_SELECTED_EVENT";
export const FETCH_EVENTS_BOOKED = "FETCH_EVENTS_BOOKED";
export const FETCH_EVENTS_BOOKED_SUCCESS = "FETCH_EVENTS_BOOKED_SUCCESS";
export const FETCH_EVENTS_BOOKED_FAIL = "FETCH_EVENTS_BOOKED_FAIL";
export const BOOK_EVENT = "BOOK_EVENT";
export const BOOK_EVENT_SUCCESS = "BOOK_EVENT_SUCCESS";
export const BOOK_EVENT_FAIL = "BOOK_EVENT_FAIL";
export const CANCEL_EVENT = "CANCEL_EVENT";
export const CANCEL_EVENT_SUCCESS = "CANCEL_EVENT_SUCCESS";
export const CANCEL_EVENT_FAIL = "CANCEL_EVENT_FAIL";

// Packs

export const PACKS_FETCH = "PACKS_FETCH";
export const PACKS_SUCCESS = "PACKS_LOADED";
export const PACKS_FAIL = "PACKS_FAIL";
export const CREATE_PACK = "CREATE_PACK";
export const CREATE_PACK_SUCCESS = "CREATE_PACK_SUCCESS";
export const CREATE_PACK_FAIL = "CREATE_PACK_FAIL";


// Pack

export const PACK_FETCH = "PACK_FETCH";
export const PACK_SUCCESS = "PACK_LOADED";
export const PACK_FAIL = "PACK_FAIL";
export const PACK_PICTURE_UPLOAD = "PACK_PICTURE_UPLOAD";
export const PACK_PICTURE_SUCCESS = "PACK_PICTURE_SUCCESS";
export const PACK_PICTURE_FAIL = "PACK_PICTURE_FAIL";
export const PACK_SAVE = "PACK_SAVE";
export const PACK_SAVE_SUCCESS = "PACK_SAVE_SUCCESS";
export const PACK_SAVE_FAIL = "PACK_SAVE_FAIL";
export const PACK_PUBLISH = "PACK_PUBLISH";
export const PACK_PUBLISH_SUCCESS = "PACK_PUBLISH_SUCCESS";
export const PACK_PUBLISH_FAIL = "PACK_PUBLISH_FAIL";
export const PACK_CANCEL_PUBLISH = "PACK_CANCEL_PUBLISH";
export const PACK_CANCEL_PUBLISH_SUCCESS = "PACK_CANCEL_PUBLISH_SUCCESS";
export const PACK_CANCEL_PUBLISH_FAIL = "PACK_CANCEL_PUBLISH_FAIL";
export const REMOVE_PACK = "REMOVE_PACK";
export const REMOVE_PACK_SUCCESS = "REMOVE_PACK_SUCCESS";
export const REMOVE_PACK_FAIL = "REMOVE_PACK_FAIL";
export const RESET_PACKS_ERRORS = "RESET_PACKS_ERRORS";

// Videos Pack

export const VIDEOS_PACK_FETCH = "VIDEOS_PACK_FETCH";
export const VIDEOS_PACK_SUCCESS = "VIDEOS_PACK_LOADED";
export const VIDEOS_PACK_FAIL = "VIDEOS_PACK_FAIL";
export const VIDEOS_PACK_ADD = "VIDEOS_PACK_ADD";
export const VIDEOS_PACK_ADD_SUCCESS = "VIDEOS_PACK_ADD_LOADED";
export const VIDEOS_PACK_ADD_FAIL = "VIDEOS_PACK_ADD_FAIL";
export const VIDEOS_PACK_REMOVE = "VIDEOS_PACK_REMOVE";
export const VIDEOS_PACK_REMOVE_SUCCESS = "VIDEOS_PACK_REMOVE_LOADED";
export const VIDEOS_PACK_REMOVE_FAIL = "VIDEOS_PACK_REMOVE_FAIL";

// Podcasts Pack

export const PODCASTS_PACK_FETCH = "PODCASTS_PACK_FETCH";
export const PODCASTS_PACK_SUCCESS = "PODCASTS_PACK_LOADED";
export const PODCASTS_PACK_FAIL = "PODCASTS_PACK_FAIL";
export const PODCASTS_PACK_ADD = "PODCASTS_PACK_ADD";
export const PODCASTS_PACK_ADD_SUCCESS = "PODCASTS_PACK_ADD_LOADED";
export const PODCASTS_PACK_ADD_FAIL = "PODCASTS_PACK_ADD_FAIL";
export const PODCASTS_PACK_REMOVE = "PODCASTS_PACK_REMOVE";
export const PODCASTS_PACK_REMOVE_SUCCESS = "PODCASTS_PACK_REMOVE_LOADED";
export const PODCASTS_PACK_REMOVE_FAIL = "PODCASTS_PACK_REMOVE_FAIL";


// Buy Packs
export const SET_SELECTED_PACK = "SET_SELECTED_PACK";
export const FETCH_PUBLISHED_PACKS = "FETCH_PUBLISHED_PACKS";
export const FETCH_PUBLISHED_PACKS_SUCCESS = "FETCH_PUBLISHED_PACKS_SUCCESS";
export const FETCH_PUBLISHED_PACKS_FAIL = "FETCH_PUBLISHED_PACKS_FAIL";
export const FETCH_MY_PACKS = "FETCH_MY_PACKS";
export const FETCH_MY_PACKS_SUCCESS = "FETCH_MY_PACKS_SUCCESS";
export const FETCH_MY_PACKS_FAIL = "FETCH_MY_PACKS_FAIL";
export const BUY_PACK = "BUY_PACK";
export const BUY_PACK_SUCCESS = "BUY_PACK_SUCCESS";
export const BUY_PACK_FAIL = "BUY_PACK_FAIL";
export const CANCEL_PACK = "CANCEL_PACK";
export const CANCEL_PACK_SUCCESS = "CANCEL_PACK_SUCCESS";
export const CANCEL_PACK_FAIL = "CANCEL_PACK_FAIL";

// Student Packs
export const STUDENT_PACK_FETCH = "STUDENT_PACK_FETCH";
export const STUDENT_PACK_SUCCESS = "STUDENT_PACK_SUCCESS";
export const STUDENT_PACK_FAIL = "STUDENT_PACK_FAIL";

// Student Video Pack

export const STUDENT_VIDEOS_PACK_FETCH = "STUDENT_VIDEOS_PACK_FETCH";
export const STUDENT_VIDEOS_PACK_SUCCESS = "STUDENT_VIDEOS_PACK_SUCCESS";
export const STUDENT_VIDEOS_PACK_FAIL = "STUDENT_VIDEOS_PACK_FAIL";
export const PLAY_STUDENT_VIDEO_PACK = "PLAY_STUDENT_VIDEO_PACK";
export const STOP_STUDENT_VIDEO_PACK = "STOP_STUDENT_VIDEO_PACK";

// Student Podcasts  Pack
export const STUDENT_PODCASTS_PACK_FETCH = "STUDENT_PODCASTS_PACK_FETCH";
export const STUDENT_PODCASTS_PACK_SUCCESS = "STUDENT_PODCASTS_PACK_SUCCESS";
export const STUDENT_PODCASTS_PACK_FAIL = "STUDENT_PODCASTS_PACK_FAIL";
export const PLAY_STUDENT_PODCAST_PACK = "PLAY_STUDENT_PODCAST_PACK";
export const STOP_STUDENT_PODCAST_PACK = "STOP_STUDENT_PODCAST_PACK";
